name: money_item
version: '1.0-SNAPSHOT'
main: org.meteorfish.money_item.Money_item
api-version: '1.21'
commands:
  tdeposit:
    usage: "/<tdeposit|출금> <출금 단위> <출금 화폐 개수>"
    description: 돈을 인출합니다
    aliases:
      - 출금
